import * as fs from "fs";
import * as path from "path";
import { config as dotenvConfig } from "dotenv";
import deployStylusContract from "./deploy_contract";
import { generateAbis } from "./generateabis";
import initContracts from "./init_contracts";
import { getDeploymentConfig, getRpcUrlFromChain, printDeployedAddresses } from "./utils/";
import type { DeployOptions } from "./utils/type";

const envPath = path.resolve(__dirname, "../.env");
if (fs.existsSync(envPath)) {
  dotenvConfig({ path: envPath });
}

const DEPLOYED_CONTRACTS_PATH = path.resolve(__dirname, "../../nextjs/contracts/deployedContracts.ts");

const FILE_HEADER = `/**
 * This file is autogenerated by scaffold-stylus.
 * You should not edit it manually or your changes might be overwritten.
 */
import type { GenericContractsDeclaration } from "../utils/scaffold-eth/contract";
`;

const FILE_FOOTER = `export default deployedContracts satisfies GenericContractsDeclaration;\n`;

// Contract name mapping: Cargo name (kebab-case) → TypeScript name (PascalCase)
const NAME_MAP: Record<string, string> = {
  "credit-manager": "CreditManager",
  "user-registry": "UserRegistry",
  "memory-registry": "MemoryRegistry",
  "agent-registry": "AgentRegistry",
  "chat-registry": "ChatRegistry",
  "context-registry": "ContextRegistry",
  "audit-registry": "AuditRegistry",
};

/**
 * Generate deployedContracts.ts from scratch using deployment JSON + ABI files.
 * This runs after all contracts are deployed, even when ABI export was skipped.
 */
function updateDeployedAddresses(chainId: string, deploymentDir: string) {
  const deploymentFile = path.resolve(deploymentDir, `${chainId}_latest.json`);
  if (!fs.existsSync(deploymentFile)) {
    console.warn(`⚠️  No deployment file found at ${deploymentFile}`);
    return;
  }

  const deployments = JSON.parse(fs.readFileSync(deploymentFile, "utf8"));
  const chainObj: Record<string, { address: string; abi: unknown[] }> = {};

  for (const [cargoName, data] of Object.entries(deployments)) {
    const tsName = NAME_MAP[cargoName];
    if (!tsName) continue;

    const deployData = data as { address: string; txHash: string; contract: string };

    // Try to read ABI from file — supports both raw JSON and cargo stylus export-abi format
    let abi: unknown[] = [];
    const abiFilePath = path.resolve(deploymentDir, cargoName);
    if (fs.existsSync(abiFilePath)) {
      try {
        const raw = fs.readFileSync(abiFilePath, "utf8");
        const trimmed = raw.trim();
        if (trimmed.startsWith("[")) {
          // Raw JSON array (from generateabis.ts)
          abi = JSON.parse(trimmed);
        } else {
          // cargo stylus export-abi --json format: 3 header lines then JSON
          const lines = trimmed.split("\n");
          const abiText = lines.slice(3).join("\n");
          abi = JSON.parse(abiText);
        }
      } catch {
        console.warn(`⚠️  Could not parse ABI file for ${cargoName}, using empty ABI`);
      }
    }

    chainObj[tsName] = { address: deployData.address, abi };
  }

  const output = `${FILE_HEADER}const deployedContracts = ${JSON.stringify({ [chainId]: chainObj }, null, 2)} as const;\n\n${FILE_FOOTER}`;

  fs.writeFileSync(DEPLOYED_CONTRACTS_PATH, output);
  const count = Object.keys(chainObj).length;
  console.log(`📝 Generated deployedContracts.ts with ${count} contracts for chain ${chainId}`);
}

/**
 * Deploy all MemoryChain contracts in dependency order.
 * Each deployStylusContract() call:
 * 1. Deploys the contract via cargo stylus
 * 2. Exports ABI via cargo stylus export-abi
 * 3. Writes ABI + address to packages/nextjs/contracts/deployedContracts.ts
 */
export default async function deployScript(deployOptions: DeployOptions) {
  const config = getDeploymentConfig(deployOptions);

  console.log(`📡 Using endpoint: ${getRpcUrlFromChain(config.chain)}`);
  if (config.chain) {
    console.log(`🌐 Network: ${config.chain?.name}`);
    console.log(`🔗 Chain ID: ${config.chain?.id}`);
  }
  console.log(`🔑 Using private key: ${config.privateKey.substring(0, 10)}...`);
  console.log(`📁 Deployment directory: ${config.deploymentDir}`);
  console.log(`\n`);

  // Deploy contracts in dependency order
  const contracts = [
    { name: "credit-manager", args: [] },
    { name: "user-registry", args: [] },
    { name: "memory-registry", args: [] },
    { name: "agent-registry", args: [] },
    { name: "chat-registry", args: [] },
    { name: "context-registry", args: [] },
    { name: "audit-registry", args: [] },
  ];

  for (const contract of contracts) {
    await deployStylusContract({
      contract: contract.name,
      constructorArgs: contract.args,
      ...deployOptions,
    });
  }

  // Print the deployed addresses
  console.log("\n\n");
  printDeployedAddresses(config.deploymentDir, config.chain.id.toString());

  // Generate ABIs from hardcoded definitions (cargo stylus export-abi fails on Nitro dev)
  generateAbis(config.deploymentDir);

  // Generate deployedContracts.ts with addresses + ABIs
  updateDeployedAddresses(config.chain.id.toString(), config.deploymentDir);

  // Initialize contracts and authorize cross-contract calls (idempotent)
  try {
    await initContracts();
  } catch (error) {
    console.error("⚠️  Contract initialization failed:", (error as Error).message);
    console.log("   You can manually initialize later by running: pnpm init-contracts");
  }
}

if (require.main === module) {
  const chainId = process.argv[2] || "412346";
  const deploymentDir = process.argv[3] || path.resolve(__dirname, "../deployments");
  updateDeployedAddresses(chainId, deploymentDir);
}

