const fs = require('fs');
const path = require('path');

const deployments = JSON.parse(fs.readFileSync('deployments/412346_latest.json', 'utf8'));
const chainId = '412346';
const NAME_MAP = {
  'credit-manager': 'CreditManager',
  'user-registry': 'UserRegistry',
  'memory-registry': 'MemoryRegistry',
  'agent-registry': 'AgentRegistry',
  'context-registry': 'ContextRegistry',
  'audit-registry': 'AuditRegistry',
};

const chainObj = {};
for (const [cargoName, data] of Object.entries(deployments)) {
  const tsName = NAME_MAP[cargoName];
  if (!tsName) continue;
  let abi = [];
  const abiPath = path.resolve('deployments', cargoName);
  if (fs.existsSync(abiPath)) {
    const raw = fs.readFileSync(abiPath, 'utf8').trim();
    if (raw.startsWith('[')) abi = JSON.parse(raw);
  }
  chainObj[tsName] = { address: data.address, abi };
}

const header = `/**
 * This file is autogenerated by scaffold-stylus.
 * You should not edit it manually or your changes might be overwritten.
 */
import type { GenericContractsDeclaration } from "../utils/scaffold-eth/contract";
`;
const footer = `export default deployedContracts satisfies GenericContractsDeclaration;\n`;

const output = header + `const deployedContracts = ${JSON.stringify({ [chainId]: chainObj }, null, 2)} as const;\n\n` + footer;
fs.writeFileSync(path.resolve(__dirname, '../../nextjs/contracts/deployedContracts.ts'), output);
console.log(`deployedContracts.ts generated with ${Object.keys(chainObj).length} contracts`);
