/**
 * This file is autogenerated by scaffold-stylus.
 * You should not edit it manually or your changes might be overwritten.
 */
import type { GenericContractsDeclaration } from "../utils/scaffold-eth/contract";
const deployedContracts = {
  "412346": {
    "CreditManager": {
      "address": "0x9268bb5c5f6403ff02a89dcff7ddbb07ff046f99",
      "abi": [
        {
          "type": "function",
          "name": "initialize",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "pause",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "unpause",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "isPaused",
          "inputs": [],
          "outputs": [
            {
              "type": "bool"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "proposeAdmin",
          "inputs": [
            {
              "name": "newAdmin",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "acceptAdmin",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "pendingAdmin",
          "inputs": [],
          "outputs": [
            {
              "type": "address"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "initializeNetwork",
          "inputs": [
            {
              "name": "isTestnet",
              "type": "bool"
            },
            {
              "name": "treasury",
              "type": "address"
            },
            {
              "name": "pricePerCredit",
              "type": "uint256"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "buyCredits",
          "inputs": [
            {
              "name": "amount",
              "type": "uint64"
            }
          ],
          "outputs": [],
          "stateMutability": "payable"
        },
        {
          "type": "function",
          "name": "consumeCredits",
          "inputs": [
            {
              "name": "user",
              "type": "address"
            },
            {
              "name": "amount",
              "type": "uint64"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "consumeCreditsForOp",
          "inputs": [
            {
              "name": "user",
              "type": "address"
            },
            {
              "name": "operation",
              "type": "uint8"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "refundCredits",
          "inputs": [
            {
              "name": "user",
              "type": "address"
            },
            {
              "name": "amount",
              "type": "uint64"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "setFee",
          "inputs": [
            {
              "name": "operation",
              "type": "uint8"
            },
            {
              "name": "fee",
              "type": "uint16"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "setPricePerCredit",
          "inputs": [
            {
              "name": "priceWei",
              "type": "uint256"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "setTreasury",
          "inputs": [
            {
              "name": "treasury",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "setPurchaseLimits",
          "inputs": [
            {
              "name": "min",
              "type": "uint64"
            },
            {
              "name": "max",
              "type": "uint64"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "setTestnetMode",
          "inputs": [
            {
              "name": "isTestnet",
              "type": "bool"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "authorizeConsumer",
          "inputs": [
            {
              "name": "consumer",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "revokeConsumer",
          "inputs": [
            {
              "name": "consumer",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "balanceOf",
          "inputs": [
            {
              "name": "user",
              "type": "address"
            }
          ],
          "outputs": [
            {
              "type": "uint64"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "totalPurchased",
          "inputs": [
            {
              "name": "user",
              "type": "address"
            }
          ],
          "outputs": [
            {
              "type": "uint64"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "totalSpent",
          "inputs": [
            {
              "name": "user",
              "type": "address"
            }
          ],
          "outputs": [
            {
              "type": "uint64"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "hasSufficientCredits",
          "inputs": [
            {
              "name": "user",
              "type": "address"
            },
            {
              "name": "amount",
              "type": "uint64"
            }
          ],
          "outputs": [
            {
              "type": "bool"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getFee",
          "inputs": [
            {
              "name": "operation",
              "type": "uint8"
            }
          ],
          "outputs": [
            {
              "type": "uint16"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getFees",
          "inputs": [],
          "outputs": [
            {
              "type": "uint16"
            },
            {
              "type": "uint16"
            },
            {
              "type": "uint16"
            },
            {
              "type": "uint16"
            },
            {
              "type": "uint16"
            },
            {
              "type": "uint16"
            },
            {
              "type": "uint16"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getPricing",
          "inputs": [],
          "outputs": [
            {
              "type": "bool"
            },
            {
              "type": "address"
            },
            {
              "type": "uint256"
            },
            {
              "type": "uint256"
            },
            {
              "type": "uint256"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "isTestnet",
          "inputs": [],
          "outputs": [
            {
              "type": "bool"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getTreasury",
          "inputs": [],
          "outputs": [
            {
              "type": "address"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getPricePerCredit",
          "inputs": [],
          "outputs": [
            {
              "type": "uint256"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "admin",
          "inputs": [],
          "outputs": [
            {
              "type": "address"
            }
          ],
          "stateMutability": "view"
        }
      ]
    },
    "UserRegistry": {
      "address": "0xacca32fccaf3220c1a3a31f7a5f879c231320642",
      "abi": [
        {
          "type": "function",
          "name": "initialize",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "pause",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "unpause",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "isPaused",
          "inputs": [],
          "outputs": [
            {
              "type": "bool"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "proposeAdmin",
          "inputs": [
            {
              "name": "newAdmin",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "acceptAdmin",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "pendingAdmin",
          "inputs": [],
          "outputs": [
            {
              "type": "address"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "registerUser",
          "inputs": [
            {
              "name": "username",
              "type": "string"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "updateUsername",
          "inputs": [
            {
              "name": "newUsername",
              "type": "string"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "deactivateUser",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "incrementAgents",
          "inputs": [
            {
              "name": "owner",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "incrementMemories",
          "inputs": [
            {
              "name": "owner",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "authorizeUpdater",
          "inputs": [
            {
              "name": "updater",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "revokeUpdater",
          "inputs": [
            {
              "name": "updater",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "exists",
          "inputs": [
            {
              "name": "owner",
              "type": "address"
            }
          ],
          "outputs": [
            {
              "type": "bool"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "isRegistered",
          "inputs": [
            {
              "name": "owner",
              "type": "address"
            }
          ],
          "outputs": [
            {
              "type": "bool"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getUsername",
          "inputs": [
            {
              "name": "owner",
              "type": "address"
            }
          ],
          "outputs": [
            {
              "type": "string"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "isActive",
          "inputs": [
            {
              "name": "owner",
              "type": "address"
            }
          ],
          "outputs": [
            {
              "type": "bool"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "totalUsers",
          "inputs": [],
          "outputs": [
            {
              "type": "uint256"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getAgentCount",
          "inputs": [
            {
              "name": "owner",
              "type": "address"
            }
          ],
          "outputs": [
            {
              "type": "uint32"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getMemoryCount",
          "inputs": [
            {
              "name": "owner",
              "type": "address"
            }
          ],
          "outputs": [
            {
              "type": "uint32"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "incrementChats",
          "inputs": [
            {
              "name": "owner",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "decrementChats",
          "inputs": [
            {
              "name": "owner",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "getChatCount",
          "inputs": [
            {
              "name": "owner",
              "type": "address"
            }
          ],
          "outputs": [
            {
              "type": "uint32"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "admin",
          "inputs": [],
          "outputs": [
            {
              "type": "address"
            }
          ],
          "stateMutability": "view"
        }
      ]
    },
    "MemoryRegistry": {
      "address": "0xc6464a3072270a3da814bb0ec2907df935ff839d",
      "abi": [
        {
          "type": "function",
          "name": "initialize",
          "inputs": [
            {
              "name": "creditManager",
              "type": "address"
            },
            {
              "name": "userRegistry",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "pause",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "unpause",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "isPaused",
          "inputs": [],
          "outputs": [
            {
              "type": "bool"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "proposeAdmin",
          "inputs": [
            {
              "name": "newAdmin",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "acceptAdmin",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "pendingAdmin",
          "inputs": [],
          "outputs": [
            {
              "type": "address"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "createMemory",
          "inputs": [
            {
              "name": "name",
              "type": "string"
            },
            {
              "name": "cid",
              "type": "string"
            },
            {
              "name": "hash",
              "type": "bytes32"
            },
            {
              "name": "memoryType",
              "type": "uint8"
            },
            {
              "name": "vis",
              "type": "uint8"
            }
          ],
          "outputs": [
            {
              "type": "bytes32"
            }
          ],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "updateMemory",
          "inputs": [
            {
              "name": "memoryId",
              "type": "bytes32"
            },
            {
              "name": "newCid",
              "type": "string"
            },
            {
              "name": "newHash",
              "type": "bytes32"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "archiveMemory",
          "inputs": [
            {
              "name": "memoryId",
              "type": "bytes32"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "restoreMemory",
          "inputs": [
            {
              "name": "memoryId",
              "type": "bytes32"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "getMemory",
          "inputs": [
            {
              "name": "memoryId",
              "type": "bytes32"
            }
          ],
          "outputs": [
            {
              "type": "address"
            },
            {
              "type": "uint32"
            },
            {
              "type": "string"
            },
            {
              "type": "bytes32"
            },
            {
              "type": "string"
            },
            {
              "type": "uint8"
            },
            {
              "type": "uint8"
            },
            {
              "type": "uint8"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "totalMemories",
          "inputs": [],
          "outputs": [
            {
              "type": "uint256"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "creditManager",
          "inputs": [],
          "outputs": [
            {
              "type": "address"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "admin",
          "inputs": [],
          "outputs": [
            {
              "type": "address"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getMemoryCountByOwner",
          "inputs": [
            {
              "name": "owner",
              "type": "address"
            }
          ],
          "outputs": [
            {
              "type": "uint256"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getMemoryByOwnerIndex",
          "inputs": [
            {
              "name": "owner",
              "type": "address"
            },
            {
              "name": "index",
              "type": "uint256"
            }
          ],
          "outputs": [
            {
              "type": "bytes32"
            }
          ],
          "stateMutability": "view"
        }
      ]
    },
    "AgentRegistry": {
      "address": "0xe7e96cef8812d2d24add2de592b5c786f915f64b",
      "abi": [
        {
          "type": "function",
          "name": "initialize",
          "inputs": [
            {
              "name": "creditManager",
              "type": "address"
            },
            {
              "name": "userRegistry",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "pause",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "unpause",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "isPaused",
          "inputs": [],
          "outputs": [
            {
              "type": "bool"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "proposeAdmin",
          "inputs": [
            {
              "name": "newAdmin",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "acceptAdmin",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "pendingAdmin",
          "inputs": [],
          "outputs": [
            {
              "type": "address"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "createAgent",
          "inputs": [
            {
              "name": "name",
              "type": "string"
            },
            {
              "name": "cid",
              "type": "string"
            },
            {
              "name": "hash",
              "type": "bytes32"
            }
          ],
          "outputs": [
            {
              "type": "bytes32"
            }
          ],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "updateAgent",
          "inputs": [
            {
              "name": "agentId",
              "type": "bytes32"
            },
            {
              "name": "newCid",
              "type": "string"
            },
            {
              "name": "newHash",
              "type": "bytes32"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "archiveAgent",
          "inputs": [
            {
              "name": "agentId",
              "type": "bytes32"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "restoreAgent",
          "inputs": [
            {
              "name": "agentId",
              "type": "bytes32"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "getAgent",
          "inputs": [
            {
              "name": "agentId",
              "type": "bytes32"
            }
          ],
          "outputs": [
            {
              "type": "address"
            },
            {
              "type": "uint32"
            },
            {
              "type": "string"
            },
            {
              "type": "bytes32"
            },
            {
              "type": "string"
            },
            {
              "type": "uint8"
            },
            {
              "type": "uint64"
            },
            {
              "type": "uint64"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "totalAgents",
          "inputs": [],
          "outputs": [
            {
              "type": "uint256"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "admin",
          "inputs": [],
          "outputs": [
            {
              "type": "address"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getAgentCountByOwner",
          "inputs": [
            {
              "name": "owner",
              "type": "address"
            }
          ],
          "outputs": [
            {
              "type": "uint256"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getAgentByOwnerIndex",
          "inputs": [
            {
              "name": "owner",
              "type": "address"
            },
            {
              "name": "index",
              "type": "uint256"
            }
          ],
          "outputs": [
            {
              "type": "bytes32"
            }
          ],
          "stateMutability": "view"
        }
      ]
    },
    "ChatRegistry": {
      "address": "0x47b8399a8a3ad9665e4257904f99eafe043c4f50",
      "abi": [
        {
          "type": "function",
          "name": "initialize",
          "inputs": [
            {
              "name": "creditManager",
              "type": "address"
            },
            {
              "name": "userRegistry",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "pause",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "unpause",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "isPaused",
          "inputs": [],
          "outputs": [
            {
              "type": "bool"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "proposeAdmin",
          "inputs": [
            {
              "name": "newAdmin",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "acceptAdmin",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "pendingAdmin",
          "inputs": [],
          "outputs": [
            {
              "type": "address"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "setCreditManager",
          "inputs": [
            {
              "name": "newAddress",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "setUserRegistry",
          "inputs": [
            {
              "name": "newAddress",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "createChat",
          "inputs": [
            {
              "name": "name",
              "type": "string"
            },
            {
              "name": "cid",
              "type": "string"
            },
            {
              "name": "hash",
              "type": "bytes32"
            }
          ],
          "outputs": [
            {
              "type": "bytes32"
            }
          ],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "updateChat",
          "inputs": [
            {
              "name": "chatId",
              "type": "bytes32"
            },
            {
              "name": "newCid",
              "type": "string"
            },
            {
              "name": "newHash",
              "type": "bytes32"
            },
            {
              "name": "newName",
              "type": "string"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "archiveChat",
          "inputs": [
            {
              "name": "chatId",
              "type": "bytes32"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "restoreChat",
          "inputs": [
            {
              "name": "chatId",
              "type": "bytes32"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "getChat",
          "inputs": [
            {
              "name": "chatId",
              "type": "bytes32"
            }
          ],
          "outputs": [
            {
              "type": "address"
            },
            {
              "type": "uint32"
            },
            {
              "type": "string"
            },
            {
              "type": "bytes32"
            },
            {
              "type": "string"
            },
            {
              "type": "uint8"
            },
            {
              "type": "uint64"
            },
            {
              "type": "uint64"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "totalChats",
          "inputs": [],
          "outputs": [
            {
              "type": "uint256"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "admin",
          "inputs": [],
          "outputs": [
            {
              "type": "address"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getChatCountByOwner",
          "inputs": [
            {
              "name": "owner",
              "type": "address"
            }
          ],
          "outputs": [
            {
              "type": "uint256"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getNonce",
          "inputs": [
            {
              "name": "owner",
              "type": "address"
            }
          ],
          "outputs": [
            {
              "type": "uint256"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getChatByOwnerIndex",
          "inputs": [
            {
              "name": "owner",
              "type": "address"
            },
            {
              "name": "index",
              "type": "uint256"
            }
          ],
          "outputs": [
            {
              "type": "bytes32"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "creditManager",
          "inputs": [],
          "outputs": [
            {
              "type": "address"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "userRegistry",
          "inputs": [],
          "outputs": [
            {
              "type": "address"
            }
          ],
          "stateMutability": "view"
        }
      ]
    },
    "ContextRegistry": {
      "address": "0xec6c3df641bde740992898f25a780aab35d0062f",
      "abi": [
        {
          "type": "function",
          "name": "initialize",
          "inputs": [
            {
              "name": "memoryRegistry",
              "type": "address"
            },
            {
              "name": "agentRegistry",
              "type": "address"
            },
            {
              "name": "creditManager",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "pause",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "unpause",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "isPaused",
          "inputs": [],
          "outputs": [
            {
              "type": "bool"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "proposeAdmin",
          "inputs": [
            {
              "name": "newAdmin",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "acceptAdmin",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "pendingAdmin",
          "inputs": [],
          "outputs": [
            {
              "type": "address"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "linkMemory",
          "inputs": [
            {
              "name": "agentId",
              "type": "bytes32"
            },
            {
              "name": "memoryId",
              "type": "bytes32"
            },
            {
              "name": "priority",
              "type": "uint8"
            }
          ],
          "outputs": [
            {
              "type": "bytes32"
            }
          ],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "unlinkMemory",
          "inputs": [
            {
              "name": "agentId",
              "type": "bytes32"
            },
            {
              "name": "memoryId",
              "type": "bytes32"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "changePriority",
          "inputs": [
            {
              "name": "contextId",
              "type": "bytes32"
            },
            {
              "name": "newPriority",
              "type": "uint8"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "disableLink",
          "inputs": [
            {
              "name": "contextId",
              "type": "bytes32"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "enableLink",
          "inputs": [
            {
              "name": "contextId",
              "type": "bytes32"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "getLink",
          "inputs": [
            {
              "name": "agentId",
              "type": "bytes32"
            },
            {
              "name": "memoryId",
              "type": "bytes32"
            }
          ],
          "outputs": [
            {
              "type": "bytes32"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getContext",
          "inputs": [
            {
              "name": "contextId",
              "type": "bytes32"
            }
          ],
          "outputs": [
            {
              "type": "bytes32"
            },
            {
              "type": "bytes32"
            },
            {
              "type": "uint8"
            },
            {
              "type": "bool"
            },
            {
              "type": "uint64"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "admin",
          "inputs": [],
          "outputs": [
            {
              "type": "address"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getAgentContextCount",
          "inputs": [
            {
              "name": "agentId",
              "type": "bytes32"
            }
          ],
          "outputs": [
            {
              "type": "uint256"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "getAgentContextByIndex",
          "inputs": [
            {
              "name": "agentId",
              "type": "bytes32"
            },
            {
              "name": "index",
              "type": "uint256"
            }
          ],
          "outputs": [
            {
              "type": "bytes32"
            }
          ],
          "stateMutability": "view"
        }
      ]
    },
    "AuditRegistry": {
      "address": "0xe7e8b4930802ce5909cb2a2b8d2e447837158660",
      "abi": [
        {
          "type": "function",
          "name": "initialize",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "pause",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "unpause",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "isPaused",
          "inputs": [],
          "outputs": [
            {
              "type": "bool"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "proposeAdmin",
          "inputs": [
            {
              "name": "newAdmin",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "acceptAdmin",
          "inputs": [],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "pendingAdmin",
          "inputs": [],
          "outputs": [
            {
              "type": "address"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "recordAudit",
          "inputs": [
            {
              "name": "actor",
              "type": "address"
            },
            {
              "name": "entityType",
              "type": "uint8"
            },
            {
              "name": "entityId",
              "type": "bytes32"
            },
            {
              "name": "action",
              "type": "uint8"
            }
          ],
          "outputs": [
            {
              "type": "bytes32"
            }
          ],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "getAuditEvent",
          "inputs": [
            {
              "name": "eventId",
              "type": "bytes32"
            }
          ],
          "outputs": [
            {
              "type": "address"
            },
            {
              "type": "uint8"
            },
            {
              "type": "bytes32"
            },
            {
              "type": "uint8"
            },
            {
              "type": "uint64"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "totalEvents",
          "inputs": [],
          "outputs": [
            {
              "type": "uint256"
            }
          ],
          "stateMutability": "view"
        },
        {
          "type": "function",
          "name": "authorizeRecorder",
          "inputs": [
            {
              "name": "recorder",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "revokeRecorder",
          "inputs": [
            {
              "name": "recorder",
              "type": "address"
            }
          ],
          "outputs": [],
          "stateMutability": "nonpayable"
        },
        {
          "type": "function",
          "name": "admin",
          "inputs": [],
          "outputs": [
            {
              "type": "address"
            }
          ],
          "stateMutability": "view"
        }
      ]
    }
  }
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
