export const SIGNS = {
  brain: { src: "/sprites/signs/memorychain-brain.svg", alt: "Brain" },
  shield: { src: "/sprites/signs/memorychain-shield.svg", alt: "Shield" },
  shieldLock: { src: "/sprites/signs/memorychain-shield-lock.svg", alt: "Shield Lock" },
  padlock: { src: "/sprites/signs/memorychain-padlock.svg", alt: "Padlock" },
  padlockBadge: { src: "/sprites/signs/memorychain-padlock-badge.svg", alt: "Padlock Badge" },
  chainLink: { src: "/sprites/signs/memorychain-chain-link.svg", alt: "Chain Link" },
  chainDecentralized: { src: "/sprites/signs/memorychain-chain-decentralized.svg", alt: "Decentralized" },
  wallet: { src: "/sprites/signs/memorychain-wallet.svg", alt: "Wallet" },
  memoryChip: { src: "/sprites/signs/memorychain-memory-chip.svg", alt: "Memory Chip" },
  memory: { src: "/sprites/signs/memorychain-memory.svg", alt: "Memory" },
  interoperable: { src: "/sprites/signs/memorychain-interoperable.svg", alt: "Interoperable" },
  user: { src: "/sprites/signs/memorychain-user.svg", alt: "User" },
  code: { src: "/sprites/signs/memorychain-code.svg", alt: "Code" },
  search: { src: "/sprites/signs/memorychain-search.svg", alt: "Search" },
  network: { src: "/sprites/signs/memorychain-network.svg", alt: "Network" },
  creditsCoin: { src: "/sprites/signs/memorychain-credits-coin.svg", alt: "Credits" },
  aiAgent: { src: "/sprites/signs/memorychain-ai-agent.svg", alt: "AI Agent" },
  sparkleStar: { src: "/sprites/signs/memorychain-sparkle-star.svg", alt: "Sparkle" },
  encryption: { src: "/sprites/signs/memorychain-encryption.svg", alt: "Encryption" },
  globe: { src: "/sprites/signs/memorychain-globe.svg", alt: "Globe" },
  lightning: { src: "/sprites/signs/memorychain-lightning.svg", alt: "Lightning" },
  key: { src: "/sprites/signs/memorychain-key.svg", alt: "Key" },
  eye: { src: "/sprites/signs/memorychain-eye.svg", alt: "Eye" },
  cube: { src: "/sprites/signs/memorychain-cube.svg", alt: "Cube" },
  document: { src: "/sprites/signs/memorychain-document.svg", alt: "Document" },
  check: { src: "/sprites/signs/memorychain-check.svg", alt: "Check" },
  clock: { src: "/sprites/signs/memorychain-clock.svg", alt: "Clock" },
  history: { src: "/sprites/signs/memorychain-history.svg", alt: "History" },
  settings: { src: "/sprites/signs/memorychain-settings.svg", alt: "Settings" },
} as const;

export type SignKey = keyof typeof SIGNS;
